version: '3.8'

services:
  subscription-db:
    image: postgres:16.3
    container_name: turkcell-subscription-db
    environment:
      POSTGRES_USER: subscription
      POSTGRES_PASSWORD: subscription
      POSTGRES_DB: subscription-db
    ports:
      - "5432:5432"
    volumes:
      - sub_db_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16.3
    container_name: turkcell-payment-db
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: payment-db
    ports:
      - "5433:5432"
    volumes:
      - pay_db_data:/var/lib/postgresql/data

volumes:
  sub_db_data:
  pay_db_data:

networks:
  default:
    name: turkcell-network