apiVersion: v1
kind: Service
metadata:
  name: subscription-db-svc
  namespace: turkcell
spec:
  ports:
    - port: 5432
  selector:
    app: subscription-db
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db-svc
  namespace: turkcell
spec:
  ports:
    - port: 5432
  selector:
    app: payment-db