apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-db
  namespace: turkcell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-db
  template:
    metadata:
      labels:
        app: subscription-db
    spec:
      containers:
        - name: postgres
          image: postgres:16.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "subscription_db"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "sub123"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: subscription-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: turkcell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:16.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "payment_db"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "pay123"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: payment-db-pvc