apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subscription-db-pvc
  namespace: turkcell
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-db-pvc
  namespace: turkcell
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi